# Generated by Django 5.2.1 on 2025-07-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleresvecinosAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('duracion_horas', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Duración (horas)')),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='programado', max_length=20, verbose_name='Estado')),
                ('profesor', models.CharField(max_length=100, verbose_name='Profesor')),
                ('lugar', models.CharField(max_length=200, verbose_name='Lugar')),
                ('categoria', models.CharField(choices=[('tecnologia', 'Tecnología'), ('salud', 'Salud'), ('educacion', 'Educación'), ('arte', 'Arte y Cultura'), ('deporte', 'Deporte'), ('cocina', 'Cocina'), ('manualidades', 'Manualidades'), ('otros', 'Otros')], max_length=20, verbose_name='Categoría')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
                'ordering': ['-fecha'],
            },
        ),
    ]
