# Generated by Django 5.2.1 on 2025-07-06 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talleresvecinosAPP', '0003_profesor_alter_taller_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='telefono',
        ),
    ]
