# Generated by Django 5.2.1 on 2025-07-06 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleresvecinosAPP', '0004_remove_profesor_email_remove_profesor_especialidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
            },
        ),
        migrations.AlterField(
            model_name='taller',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresvecinosAPP.lugar', verbose_name='Lugar'),
        ),
    ]
