# Generated by Django 5.2.1 on 2025-07-06 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleresvecinosAPP', '0007_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleresvecinosAPP.lugar', verbose_name='Lugar'),
        ),
    ]
