# Generated by Django 5.2.1 on 2025-07-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleresvecinosAPP', '0011_alter_taller_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
