# Generated by Django 5.2.1 on 2025-07-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleresvecinosAPP', '0012_alter_taller_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha y Hora'),
        ),
    ]
